#!/bin/bash
# SPDX-FileCopyrightText: 2024 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Create a test environment that allows testing with calendars
#

cd "`dirname \"$0\"`"
cd ..

if ! [ -f ".tox/py39/bin/activate" ]; then
  tox -e py39
fi

(
  cd features/calendars
  python3 -m http.server 8001 &
)


source .tox/py39/bin/activate

python3 -m open_web_calendar
