#!/bin/bash
# SPDX-FileCopyrightText: 2024 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Create a test environment that allows testing with calendars
#

cd "`dirname \"$0\"`"
cd ..

(
  cd features/calendars
  python3 -m http.server 8001 &
)

source .tox/py39/bin/activate

python3 app.py
