#!/bin/bash
#
# Create a test environment that allows testing with calendars
#

cd "`dirname \"$0\"`"
cd ..

(
  cd features/calendars
  python3 -m http.server &
)

source .tox/py39/bin/activate

python3 app.py
