#!/bin/bash
# SPDX-FileCopyrightText: 2024 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>
#
# SPDX-License-Identifier: GPL-2.0-only

set -e
shopt -s globstar
cd "`dirname \"$0\"`"

translated_documentation_languages="en"

for lang in `ls ../docs/locale`; do
  [ -d "../docs/locale/$lang/LC_MESSAGES" ] || continue
  for file in index.po contributing.po ; do
    po="../docs/locale/$lang/LC_MESSAGES/$file"
    [ -f "$po" ] || continue
    msgstr_count="`grep -F 'msgstr' \"$po\" | wc -l`"
    empty_msgstr_count="`grep -F 'msgstr ""' \"$po\" | wc -l`"
    # add to count because of auto-generated messages: X-Generator
    min_messages=$(( empty_msgstr_count + 1 ))
    if test "$msgstr_count" -gt  "$min_messages" ; then
      echo -e "$lang\t has a translation in `basename \"$po\"`\t$po ($msgstr_count, $min_messages)"
      if [[ "$translated_documentation_languages" != *"$lang"* ]]; then
        translated_documentation_languages="$translated_documentation_languages $lang"
      fi
    fi
  done
done

echo "The documentation is translated into: $translated_documentation_languages"

# Emit docs/_languages.yml consumed by conf.py.
out="../docs/_languages.yml"
# REUSE-IgnoreStart
{
  echo "# SPDX-FileCopyrightText: 2026 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>"
  echo "# SPDX-License-Identifier: GPL-2.0-only"
  echo "# Auto-generated by scripts/find-translated-documentation-languages.sh"
  echo "languages:"
  for lang in $translated_documentation_languages; do
    yml="../open_web_calendar/translations/$lang/calendar.yml"
    case "$lang" in
      en) name="English" ;;
      ko_LAVA) name="한국어 (LAVA)" ;;
      zh_Hant) name="繁體中文" ;;
      zh_Hans) name="简体中文" ;;
      nb_NO) name="Norsk bokmål" ;;
      *)
        if [ -f "$yml" ]; then
          name="`grep -F 'language:' \"$yml\" | head -1 | sed -E 's/^[^:]*:[[:space:]]*//; s/^\"//; s/\"\$//'`"
        else
          name="$lang"
        fi
        ;;
    esac
    if [ -z "$name" ]; then
      echo "ERROR: Did not find a name for $lang. Add it manually." >&2
      continue
    fi
    echo "  - code: $lang"
    echo "    name: \"$name\""
  done
} > "$out"
# REUSE-IgnoreEnd

echo "Wrote $out"
